In [2]:
import pandas as pd
import json

In [12]:
with open('../data/api_football_rapid/cleaned/generics/countries.json', 'r') as f:
    countries_data = json.load(f)

countries_df = pd.DataFrame(countries_data["response"])
countries_df.head()

                  name code                                      flag
0              Albania   AL  https://media.api-sports.io/flags/al.svg
1              Algeria   DZ  https://media.api-sports.io/flags/dz.svg
2              Andorra   AD  https://media.api-sports.io/flags/ad.svg
3               Angola   AO  https://media.api-sports.io/flags/ao.svg
4  Antigua-And-Barbuda   AG  https://media.api-sports.io/flags/ag.svg

In [13]:
with open('../data/api_football_rapid/cleaned/generics/leagues.json', 'r') as f:
    countries_data = json.load(f)

countries_df = pd.DataFrame(countries_data["response"])
countries_df.head()

,league,country,seasons
0,"{'id': 4, 'name': 'Euro Championship', 'type':...","{'name': 'World', 'code': None, 'flag': None}","[{'year': 2008, 'start': '2008-06-07', 'end': ..."
1,"{'id': 21, 'name': 'Confederations Cup', 'type...","{'name': 'World', 'code': None, 'flag': None}","[{'year': 2009, 'start': '2009-06-14', 'end': ..."
2,"{'id': 61, 'name': 'Ligue 1', 'type': 'League'...","{'name': 'France', 'code': 'FR', 'flag': 'http...","[{'year': 2010, 'start': '2010-08-07', 'end': ..."
3,"{'id': 144, 'name': 'Jupiler Pro League', 'typ...","{'name': 'Belgium', 'code': 'BE', 'flag': 'htt...","[{'year': 2010, 'start': '2010-07-30', 'end': ..."
4,"{'id': 71, 'name': 'Serie A', 'type': 'League'...","{'name': 'Brazil', 'code': 'BR', 'flag': 'http...","[{'year': 2010, 'start': '2010-05-08', 'end': ..."

In [14]:
with open('../data/api_football_rapid/cleaned/generics/timezone.json', 'r') as f:
    countries_data = json.load(f)

countries_df = pd.DataFrame(countries_data["response"])
countries_df.head()

                    0
0      Africa/Abidjan
1        Africa/Accra
2  Africa/Addis_Ababa
3      Africa/Algiers
4       Africa/Asmara